### ISSUE TITLE
Wavi GetX Initialize App not work, without any error messages

### ISSUE THREAD

**Issue by Chgocn** [msilvamolina/vscode-wavi-getx-awesome#1]
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

When execute "Wavi GetX Initialize App" command,it will be get a notification with "Done!" quickly,but not generate any files.

**Comment by pinguluk** [comment]
Same

**Comment by pinguluk** [comment]
It seems there's something wrong with the paths, because on Windows it creates the files in ```C:\c%3A```, not in the actual project path.

Basically for example

Project location:
`C:\Users\pinguluk\Desktop\Bitbucket Work\example\getx structure 1\flutter_application_1`

After running the init, a new folder is created at:
`C:\c%3A\Users\pinguluk\Desktop\Bitbucket%20Work\example\getx%20structure%201\flutter_application_1`

**Comment by pinguluk** [comment]
Quick fix for Windows:
Go to `%userprofile%\.vscode\extensions\martinsilvamolina.wavi-getx-awesome-1.0.2`
And replace
```
const folderPath = vscode.workspace.workspaceFolders[0].uri
.toString()
.split(":")[1];
```
with
```
const folderPath = vscode.workspace.workspaceFolders[0].uri.fsPath;
```

for every command (5 in total)

**Comment by Chgocn** [comment]
Great! You saved my time! I also find the generated files in C:\c%3A.

**Comment by gcmenotti** [comment]
It works
